#!/bin/bash

# ============================================
# Main Setup Script for macOS Development Environment
# ============================================
# This script orchestrates the setup of:
# - Homebrew installation + packages and applications (via Brewfile)
# - mise for version management (Node, Python, Ruby, etc.)
# - GNU Stow for dotfile symlink management
# - GnuPG (GPG) for secure communications and commit signing
# - VSCode extensions
# ============================================

set -e  # Exit on error

DOTFILES_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=./scripts/lib.sh
source "$DOTFILES_DIR/scripts/lib.sh"
setup_output_colors

has_tty() {
  [[ -t 0 || -t 1 || -t 2 ]]
}

can_read_tty() {
  [[ -r /dev/tty ]] || return 1
  : </dev/tty 2>/dev/null
}

prompt_yes_no() {
  local prompt="$1"
  local default_answer="${2:-n}"
  local suffix="[y/N]"
  local default="n"

  if [[ "$default_answer" =~ ^[Yy]$ ]]; then
    suffix="[Y/n]"
    default="y"
  fi

  if has_tty && can_read_tty; then
    read -r -p "$(printf "%s %s " "$prompt" "$suffix")" answer </dev/tty || answer="$default"
    answer="${answer:-$default}"
  else
    answer="$default"
  fi

  [[ "$answer" =~ ^[Yy]$ ]]
}

prompt_with_default() {
  local prompt="$1"
  local default_value="${2:-}"
  local suffix=""
  local answer="$default_value"

  if [[ -n "$default_value" ]]; then
    suffix=" [$default_value]"
  fi

  if has_tty && can_read_tty; then
    read -r -p "$(printf "%s%s: " "$prompt" "$suffix")" input </dev/tty || input=""
    if [[ -n "$input" ]]; then
      answer="$input"
    fi
  fi

  echo "$answer"
}


DOTFILES_NONINTERACTIVE="$(normalize_bool "${DOTFILES_NONINTERACTIVE:-0}")"
export DOTFILES_NONINTERACTIVE
if [[ "$DOTFILES_NONINTERACTIVE" == "1" ]]; then
  export DOTFILES_SKIP_OPTIONAL_PROMPTS=1
  export DOTFILES_SKIP_GIT_PROMPTS=1
fi
DOTFILES_SETUP_OBSIDIAN_PLUGINS="$(normalize_bool "${DOTFILES_SETUP_OBSIDIAN_PLUGINS:-1}")"
export DOTFILES_SETUP_OBSIDIAN_PLUGINS

# Persisted optional cask preferences live outside the repo to avoid dirty git state
OPTIONAL_CASK_ENV_FILE="${OPTIONAL_CASK_ENV_FILE:-$HOME/.config/dotfiles/brew-optional.env}"
GIT_LOCAL_CONFIG_FILE="${GIT_LOCAL_CONFIG_FILE:-$HOME/.gitconfig.local}"
# Personal fallback identity defaults for this dotfiles repo owner.
# Others should override via env (GIT_USER_*) or set DEFAULT_GIT_* for their fork.
DEFAULT_GIT_NAME="${DEFAULT_GIT_NAME:-Mike Attara}"
DEFAULT_GIT_EMAIL="${DEFAULT_GIT_EMAIL:-mpyebattara@gmail.com}"
DEFAULT_GIT_SIGNINGKEY="${DEFAULT_GIT_SIGNINGKEY:-0x8C47F9FE2344DB2C}"

load_optional_cask_env() {
  if [[ -f "$OPTIONAL_CASK_ENV_FILE" ]]; then
    load_optional_cask_env_file "$OPTIONAL_CASK_ENV_FILE"
    print_info "Loaded optional cask preferences from $OPTIONAL_CASK_ENV_FILE"
  fi
}

write_optional_cask_env() {
  local entry suffix brew_var bundle_var tmp_file

  mkdir -p "$(dirname "$OPTIONAL_CASK_ENV_FILE")"
  sync_optional_cask_env_vars

  tmp_file="$(mktemp)"

  {
    echo "# Auto-generated by setup.sh - optional cask preferences"
    for entry in "${OPTIONAL_CASK_SPECS[@]}"; do
      IFS='|' read -r suffix _ _ <<< "$entry"
      brew_var="BREW_INSTALL_${suffix}"
      bundle_var="HOMEBREW_BUNDLE_INSTALL_${suffix}"
      echo "export $brew_var=${!brew_var:-0}"
      echo "export $bundle_var=${!bundle_var:-${!brew_var:-0}}"
    done
  } > "$tmp_file"

  if replace_file_if_changed "$tmp_file" "$OPTIONAL_CASK_ENV_FILE"; then
    chmod 600 "$OPTIONAL_CASK_ENV_FILE" 2>/dev/null || true
    print_success "Saved optional cask preferences to $OPTIONAL_CASK_ENV_FILE"
    return
  fi

  chmod 600 "$OPTIONAL_CASK_ENV_FILE" 2>/dev/null || true
  print_info "Optional cask preferences unchanged at $OPTIONAL_CASK_ENV_FILE"
}

install_homebrew() {
  local installer_url installer_script
  installer_url="https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh"
  installer_script="$(mktemp)"

  if ! command -v curl >/dev/null 2>&1; then
    print_error "curl is required to install Homebrew automatically."
    rm -f "$installer_script"
    exit 1
  fi

  print_info "Homebrew not found. Downloading official installer..."
  if ! curl --fail --silent --show-error --location "$installer_url" --output "$installer_script"; then
    print_error "Failed to download Homebrew installer from $installer_url"
    rm -f "$installer_script"
    exit 1
  fi

  chmod 700 "$installer_script"

  print_info "Running Homebrew installer..."
  if [[ "$DOTFILES_NONINTERACTIVE" == "1" ]]; then
    NONINTERACTIVE=1 CI=1 /bin/bash "$installer_script"
  else
    /bin/bash "$installer_script"
  fi

  rm -f "$installer_script"

  activate_homebrew_shellenv || true

  if ! command -v brew >/dev/null 2>&1; then
    print_error "Homebrew installer completed, but 'brew' is still unavailable in PATH."
    print_info "Install Homebrew manually from https://brew.sh/ and rerun setup."
    exit 1
  fi

  print_success "Homebrew installed successfully ($(brew --version | head -n 1))"
}

# ============================================
# Pre-flight checks
# ============================================

print_header "Pre-flight Checks"

# Check if running on macOS
if [[ "$OSTYPE" != "darwin"* ]]; then
  print_error "This script is designed for macOS only."
  exit 1
fi

print_success "Running on macOS"

# Ensure Xcode Command Line Tools are available for git/Homebrew
if ! xcode-select -p >/dev/null 2>&1; then
  print_info "Installing Xcode Command Line Tools..."
  xcode-select --install || true
  print_warning "Command Line Tools install has been initiated. Re-run setup after it completes."
  exit 1
fi

print_success "Xcode Command Line Tools detected"

if [[ "$DOTFILES_NONINTERACTIVE" == "1" ]]; then
  print_info "Non-interactive mode enabled (DOTFILES_NONINTERACTIVE=1); prompts and sudo refresh are disabled."
fi

load_optional_cask_env

# ============================================
# Optional cask selection (Antigravity, UTM, Brave, VLC, Spotify)
# ============================================

print_header "Optional Casks"

configure_optional_cask() {
  local var_name="$1"
  local label="$2"
  local description="$3"
  local brew_bundle_var="HOMEBREW_BUNDLE_INSTALL_${var_name#BREW_INSTALL_}"
  local current="${!var_name:-${!brew_bundle_var:-}}"
  local normalized_current
  normalized_current="$(normalize_bool "$current")"
  local default_label=$([[ "$normalized_current" == "1" ]] && echo "enabled" || echo "disabled")

  if [[ -n "$current" ]]; then
    print_info "$label default: $default_label (current setting)"
  else
    print_info "$label default: $default_label"
  fi

  # Skip prompting when explicitly requested or when no TTY is available
  if [[ "${DOTFILES_SKIP_OPTIONAL_PROMPTS:-0}" == "1" || ! has_tty ]]; then
    export "$var_name"="$normalized_current"
    export "$brew_bundle_var"="$normalized_current"
    print_info "Skipping prompt for $label; using $var_name=${!var_name} (set $var_name=1 to enable)."
    return
  fi

  local prompt_default="n"
  if [[ -n "$current" ]]; then
    prompt_default=$([[ "$normalized_current" == "1" ]] && echo "y" || echo "n")
  fi

  local prompt="Install ${label}? (${description})"
  if prompt_yes_no "$prompt" "$prompt_default"; then
    export "$var_name"=1
    export "$brew_bundle_var"=1
    print_success "$label enabled ($var_name=1)"
  else
    export "$var_name"=0
    export "$brew_bundle_var"=0
    print_info "$label skipped ($var_name=0)"
  fi
}

for cask_spec in "${OPTIONAL_CASK_SPECS[@]}"; do
  IFS='|' read -r cask_suffix cask_label cask_description <<< "$cask_spec"
  configure_optional_cask "BREW_INSTALL_${cask_suffix}" "$cask_label" "$cask_description"
done

write_optional_cask_env

# Keep sudo alive so Homebrew/cask installs only prompt once
if [[ "$DOTFILES_NONINTERACTIVE" == "1" ]]; then
  print_info "Skipping sudo credential refresh in non-interactive mode."
elif command -v sudo >/dev/null 2>&1; then
  print_info "Refreshing sudo credentials to avoid repeated prompts..."
  if sudo -v; then
    # Background keepalive until this script exits
    while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &
    SUDO_KEEPALIVE_PID=$!
    trap '[[ -n "$SUDO_KEEPALIVE_PID" ]] && kill "$SUDO_KEEPALIVE_PID" 2>/dev/null || true' EXIT
    print_success "Sudo session refreshed"
  else
    print_warning "Could not refresh sudo credentials. You may be prompted during installs."
  fi
else
  print_warning "sudo not available. Continuing without elevated privileges."
fi

print_info "Dotfiles directory: $DOTFILES_DIR"

cd "$DOTFILES_DIR"

# ============================================
# Step 1: Install Homebrew
# ============================================

print_header "Step 1: Homebrew Installation"

if ! command -v brew &> /dev/null; then
  activate_homebrew_shellenv || true
fi

if command -v brew &> /dev/null; then
  print_success "Homebrew is already installed ($(brew --version | head -n 1))"
else
  install_homebrew
fi

# ============================================
# Step 2: Install packages from Brewfile
# ============================================

print_header "Step 2: Installing Packages from Brewfile"

if [[ -f "$DOTFILES_DIR/Brewfile" ]]; then
  print_info "Running brew bundle install..."
  OPTIONAL_CASK_ENV_FILE="$OPTIONAL_CASK_ENV_FILE" \
    "$DOTFILES_DIR/scripts/brew.sh" bundle install --file="$DOTFILES_DIR/Brewfile" --verbose
  print_success "All packages installed from Brewfile"
else
  print_error "Brewfile not found at $DOTFILES_DIR/Brewfile"
  exit 1
fi

# ============================================
# Step 3: Setup mise (version manager)
# ============================================

print_header "Step 3: Setting up mise"

if [[ -f "$DOTFILES_DIR/scripts/tools.sh" ]]; then
  bash "$DOTFILES_DIR/scripts/tools.sh" mise
else
  print_warning "scripts/tools.sh not found, skipping..."
fi

# ============================================
# Step 4: Configure Git identity
# ============================================

print_header "Step 4: Configuring Git Identity"

_resolve_git_value() {
  local file_val="$1" env_val="$2" existing_val="$3" default_val="$4"
  if   [[ -n "$file_val"     ]]; then printf '%s' "$file_val"
  elif [[ -n "$env_val"      ]]; then printf '%s' "$env_val"
  elif [[ -n "$existing_val" ]]; then printf '%s' "$existing_val"
  else                                printf '%s' "$default_val"
  fi
}

configure_git_identity() {
  local env_name env_email env_signing env_signing_set
  env_name="${GIT_USER_NAME:-}"
  env_email="${GIT_USER_EMAIL:-}"
  env_signing="${GIT_USER_SIGNINGKEY:-}"
  env_signing_set="${GIT_USER_SIGNINGKEY+set}"

  local file_name file_email file_signing
  if [[ -f "$GIT_LOCAL_CONFIG_FILE" ]]; then
    file_name="$(git config --file "$GIT_LOCAL_CONFIG_FILE" --get user.name 2>/dev/null || true)"
    file_email="$(git config --file "$GIT_LOCAL_CONFIG_FILE" --get user.email 2>/dev/null || true)"
    file_signing="$(git config --file "$GIT_LOCAL_CONFIG_FILE" --get user.signingkey 2>/dev/null || true)"
  fi

  local existing_name existing_email existing_signing
  existing_name="$(git config --global --get user.name 2>/dev/null || true)"
  existing_email="$(git config --global --get user.email 2>/dev/null || true)"
  existing_signing="$(git config --global --get user.signingkey 2>/dev/null || true)"

  # Prefer saved local config, then env overrides, then current global git, then hardcoded fallback.
  # Treat empty strings as unset.
  local default_name default_email
  default_name="$(_resolve_git_value "${file_name:-}" "${env_name:-}" "${existing_name:-}" "$DEFAULT_GIT_NAME")"
  default_email="$(_resolve_git_value "${file_email:-}" "${env_email:-}" "${existing_email:-}" "$DEFAULT_GIT_EMAIL")"

  local default_signing
  if [[ "$env_signing_set" == "set" ]]; then
    default_signing="$env_signing" # allow explicit empty to disable signing
  elif [[ -n "${file_signing:-}" ]]; then
    default_signing="$file_signing"
  elif [[ -n "${existing_signing:-}" ]]; then
    default_signing="$existing_signing"
  else
    default_signing="$DEFAULT_GIT_SIGNINGKEY"
  fi

  local final_name="${env_name:-$default_name}"
  local final_email="${env_email:-$default_email}"
  local final_signing="${env_signing:-$default_signing}"

  if [[ "${DOTFILES_SKIP_GIT_PROMPTS:-0}" == "1" ]]; then
    if [[ -z "$default_name" && -z "$default_email" ]]; then
      print_info "Skipping Git identity prompts (DOTFILES_SKIP_GIT_PROMPTS=1) with no defaults; leaving existing config untouched."
      return
    fi
    print_info "Skipping Git identity prompts (DOTFILES_SKIP_GIT_PROMPTS=1); using provided defaults."
  elif ! has_tty; then
    if [[ -z "$default_name" && -z "$default_email" ]]; then
      print_info "No TTY and no defaults available; skipping Git identity configuration."
      return
    fi
  else
    if [[ -z "$env_name" || -z "$env_email" ]]; then
      local name_prompt="Git user.name"
      final_name="$(prompt_with_default "$name_prompt" "$final_name")"
      while has_tty && [[ -z "$final_name" ]]; do
        print_warning "Git user.name is required."
        final_name="$(prompt_with_default "$name_prompt" "$final_name")"
      done

      local email_prompt="Git user.email"
      final_email="$(prompt_with_default "$email_prompt" "$final_email")"
      while has_tty && [[ -z "$final_email" ]]; do
        print_warning "Git user.email is required."
        final_email="$(prompt_with_default "$email_prompt" "$final_email")"
      done

      local signing_prompt="Git signingkey (optional)"
      final_signing="$(prompt_with_default "$signing_prompt" "$final_signing")"
    else
      print_info "Using Git identity defaults without prompting (env provided)."
    fi
  fi

  if [[ -z "$final_name" || -z "$final_email" ]]; then
    print_warning "Git identity not updated (missing name/email)."
    return
  fi

  mkdir -p "$(dirname "$GIT_LOCAL_CONFIG_FILE")"
  touch "$GIT_LOCAL_CONFIG_FILE"

  # Update only the managed keys and preserve all other local custom settings.
  git config --file "$GIT_LOCAL_CONFIG_FILE" user.name "$final_name"
  git config --file "$GIT_LOCAL_CONFIG_FILE" user.email "$final_email"

  if [[ -n "$final_signing" ]]; then
    git config --file "$GIT_LOCAL_CONFIG_FILE" user.signingkey "$final_signing"
    git config --file "$GIT_LOCAL_CONFIG_FILE" commit.gpgsign true
    git config --file "$GIT_LOCAL_CONFIG_FILE" tag.gpgSign true
    git config --file "$GIT_LOCAL_CONFIG_FILE" tag.forceSignAnnotated true
  else
    git config --file "$GIT_LOCAL_CONFIG_FILE" --unset-all user.signingkey 2>/dev/null || true
    git config --file "$GIT_LOCAL_CONFIG_FILE" commit.gpgsign false
    git config --file "$GIT_LOCAL_CONFIG_FILE" tag.gpgSign false
    git config --file "$GIT_LOCAL_CONFIG_FILE" tag.forceSignAnnotated false
  fi

  print_success "Git identity configured in $GIT_LOCAL_CONFIG_FILE"
  print_info "Git user.name: $final_name"
  print_info "Git user.email: $final_email"
  if [[ -n "$final_signing" ]]; then
    print_info "Git signingkey: $final_signing"
  fi
}

configure_git_identity

# ============================================
# Step 5: Setup dotfiles with GNU Stow
# ============================================

print_header "Step 5: Setting up Dotfiles with GNU Stow"

if [[ -f "$DOTFILES_DIR/scripts/tools.sh" ]]; then
  bash "$DOTFILES_DIR/scripts/tools.sh" stow
else
  print_warning "scripts/tools.sh not found, skipping..."
fi

verify_obsidian_setup() {
  if brew list --cask obsidian >/dev/null 2>&1; then
    : # installed
  else
    print_warning "Obsidian cask not detected. Run: brew install --cask obsidian"
  fi

  local required_files=()
  local vault_seed_dir="$DOTFILES_DIR/obsidian/.knowledge"
  local lock_file="$DOTFILES_DIR/obsidian/community-plugin-lock.json"
  local file source_file rel_path

  if [[ -d "$vault_seed_dir" ]]; then
    while IFS= read -r source_file; do
      rel_path="${source_file#"$vault_seed_dir/"}"
      required_files+=("$HOME/.knowledge/$rel_path")
    done < <(find "$vault_seed_dir" -type f | sort)
  fi

  if [[ "$DOTFILES_SETUP_OBSIDIAN_PLUGINS" == "1" ]]; then
    required_files+=(
      "$HOME/.knowledge/.obsidian/core-plugins.json"
      "$HOME/.knowledge/.obsidian/templates.json"
      "$HOME/.knowledge/.obsidian/community-plugins.json"
    )

    if [[ -f "$lock_file" ]] && command -v jq >/dev/null 2>&1; then
      while IFS= read -r file; do
        [[ -n "$file" ]] && required_files+=("$file")
      done < <(
        jq -r --arg home "$HOME" \
          '.plugins | keys[] | "\($home)/.knowledge/.obsidian/plugins/\(.)/manifest.json"' \
          "$lock_file"
      )
    fi
  fi

  local missing=()

  for file in "${required_files[@]}"; do
    if [[ ! -e "$file" ]]; then
      missing+=("$file")
    fi
  done

  if [[ ${#missing[@]} -gt 0 ]]; then
    local missing_vault_files=0
    local missing_plugin_files=0

    for file in "${missing[@]}"; do
      if [[ "$file" == "$HOME/.knowledge/.obsidian/"* ]]; then
        missing_plugin_files=1
      else
        missing_vault_files=1
      fi
    done

    if [[ "$missing_vault_files" == "1" ]]; then
      print_warning "Some Obsidian vault note files are missing. Re-run: make stow"
    fi
    if [[ "$missing_plugin_files" == "1" ]]; then
      print_warning "Some Obsidian plugin files are missing. Re-run: make obsidian"
    fi

    for file in "${missing[@]}"; do
      print_warning "Missing: $file"
    done
  fi
}

print_header "Step 6: Setting up Obsidian Vault and Plugins"

if [[ -f "$DOTFILES_DIR/scripts/obsidian.sh" ]]; then
  if [[ "$DOTFILES_SETUP_OBSIDIAN_PLUGINS" == "1" ]]; then
    bash "$DOTFILES_DIR/scripts/obsidian.sh" setup
  else
    print_info "Skipping Obsidian plugin downloads (DOTFILES_SETUP_OBSIDIAN_PLUGINS=0)"
    DOTFILES_OBSIDIAN_SKIP_PLUGIN_DOWNLOADS=1 \
      bash "$DOTFILES_DIR/scripts/obsidian.sh" setup
  fi
else
  print_warning "scripts/obsidian.sh not found, skipping Obsidian setup..."
fi

verify_obsidian_setup

# ============================================
# Step 7: Setup GnuPG (GPG)
# ============================================

print_header "Step 7: Setting up GnuPG"

if [[ -f "$DOTFILES_DIR/scripts/tools.sh" ]]; then
  bash "$DOTFILES_DIR/scripts/tools.sh" gnupg
else
  print_warning "scripts/tools.sh not found, skipping..."
fi

# ============================================
# Step 8: Setup VSCode extensions
# ============================================

print_header "Step 8: Setting up VSCode Extensions"

# Allow skipping via env; otherwise auto-run if VSCode CLI is available
if [[ "${SKIP_VSCODE_EXTENSIONS:-0}" == "1" ]]; then
  print_info "Skipping VSCode extensions setup (SKIP_VSCODE_EXTENSIONS=1)"
elif ! command -v code >/dev/null 2>&1; then
  print_warning "VSCode CLI 'code' not found. Install VSCode and run: make vscode"
elif [[ -f "$DOTFILES_DIR/scripts/tools.sh" ]]; then
  bash "$DOTFILES_DIR/scripts/tools.sh" vscode
else
  print_warning "scripts/tools.sh not found, skipping..."
fi

# ============================================
# Final Steps
# ============================================

print_header "Setup Complete!"

print_mise_track_example() {
  local tool="$1"
  local label="$2"
  local config_path track

  for config_path in "$HOME/.mise.toml" "$DOTFILES_DIR/mise/.mise.toml"; do
    if track="$(mise_get_tool_track "$config_path" "$tool" 2>/dev/null)"; then
      if [[ -n "$track" ]]; then
        echo "   ${GREEN}mise use ${tool}@${track}${NC}  # Install ${label} ${track}"
        return 0
      fi
    fi
  done

  echo "   ${GREEN}mise use ${tool}@<track>${NC}  # Install ${label}"
}

echo "Your development environment has been set up successfully!"
echo ""
echo "📋 Next Steps:"
echo ""
echo "1. Restart your terminal or run:"
echo "   ${GREEN}source ~/.zshrc${NC}"
echo ""
echo "2. Verify installations:"
echo "   ${GREEN}brew doctor${NC}          # Check Homebrew health"
echo "   ${GREEN}mise doctor${NC}          # Check mise health"
echo "   ${GREEN}mise list${NC}            # Show installed versions"
echo ""
echo "3. Install additional language versions with mise:"
print_mise_track_example "node" "Node.js"
print_mise_track_example "python" "Python"
print_mise_track_example "uv" "uv"
echo "   ${GREEN}# Edit ~/.mise.toml to add/remove tools, then:${NC}"
echo "   ${GREEN}make mise${NC}"
echo ""
echo "4. Explore modern CLI helpers:"
echo "   ${GREEN}l / ll / la${NC}          # eza listings with icons and Git status"
echo "   ${GREEN}cat file.txt${NC}         # bat with syntax highlighting"
echo "   ${GREEN}z <dir>${NC}              # zoxide smart directory jump"
echo ""
echo "💡 Tips:"
echo "   - Use 'z <dir>' for smart directory jumping"
echo "   - Use 'fzf' with Ctrl+R for command history search"
echo "   - Use 'brewup' in an interactive shell to update Homebrew packages"
echo ""
echo "📖 For more information, check the README.md"
echo ""
