#!/bin/bash

# ============================================
# Main Setup Script for macOS Development Environment
# ============================================
# This script orchestrates the setup of:
# - Homebrew packages and applications (via Brewfile)
# - mise for version management (Node, Python, Ruby, etc.)
# - GNU Stow for dotfile symlink management
# - GnuPG (GPG) for secure communications and commit signing
# - VSCode extensions
# ============================================

set -e  # Exit on error

# Colors for output (auto-disable if not a TTY or NO_COLOR set)
if [[ -t 1 && -z "${NO_COLOR:-}" ]]; then
  RED=$'\033[38;5;203m'
  GREEN=$'\033[38;5;76m'
  YELLOW=$'\033[38;5;220m'
  BLUE=$'\033[38;5;69m'
  MAGENTA=$'\033[38;5;171m'
  CYAN=$'\033[38;5;45m'
  NC=$'\033[0m' # No Color
else
  RED=""
  GREEN=""
  YELLOW=""
  BLUE=""
  MAGENTA=""
  CYAN=""
  NC=""
fi

# Helper functions
print_header() {
  echo ""
  echo -e "${MAGENTA}============================================${NC}"
  echo -e "${MAGENTA}$1${NC}"
  echo -e "${MAGENTA}============================================${NC}"
  echo ""
}

print_success() {
  echo -e "${GREEN}✓${NC} $1"
}

print_error() {
  echo -e "${RED}✗${NC} $1"
}

print_warning() {
  echo -e "${YELLOW}⚠${NC} $1"
}

print_info() {
  echo -e "${BLUE}ℹ${NC} $1"
}

print_note() {
  echo -e "${CYAN}ℹ${NC} $1"
}

has_tty() {
  [[ -t 0 || -t 1 || -t 2 || -r /dev/tty ]]
}

prompt_yes_no() {
  local prompt="$1"
  local default_answer="${2:-n}"
  local suffix="[y/N]"
  local default="n"

  if [[ "$default_answer" =~ ^[Yy]$ ]]; then
    suffix="[Y/n]"
    default="y"
  fi

  if has_tty && [[ -r /dev/tty ]]; then
    read -r -p "$(printf "%s %s " "$prompt" "$suffix")" answer </dev/tty || answer="$default"
    answer="${answer:-$default}"
  else
    answer="$default"
  fi

  [[ "$answer" =~ ^[Yy]$ ]]
}

prompt_with_default() {
  local prompt="$1"
  local default_value="${2:-}"
  local suffix=""
  local answer="$default_value"

  if [[ -n "$default_value" ]]; then
    suffix=" [$default_value]"
  fi

  if has_tty && [[ -r /dev/tty ]]; then
    read -r -p "$(printf "%s%s: " "$prompt" "$suffix")" input </dev/tty || input=""
    if [[ -n "$input" ]]; then
      answer="$input"
    fi
  fi

  echo "$answer"
}

normalize_bool() {
  local raw
  raw="$(printf '%s' "${1:-}" | tr '[:upper:]' '[:lower:]')"
  case "$raw" in
    1|y|yes|true|on) echo "1" ;;
    0|n|no|false|off) echo "0" ;;
    *) echo "0" ;;
  esac
}

# Persisted optional cask preferences live outside the repo to avoid dirty git state
OPTIONAL_CASK_ENV_FILE="${OPTIONAL_CASK_ENV_FILE:-$HOME/.config/dotfiles/brew-optional.env}"
GIT_LOCAL_CONFIG_FILE="${GIT_LOCAL_CONFIG_FILE:-$HOME/.gitconfig.local}"

load_optional_cask_env() {
  if [[ -f "$OPTIONAL_CASK_ENV_FILE" ]]; then
    # shellcheck disable=SC1090
    source "$OPTIONAL_CASK_ENV_FILE"
    print_info "Loaded optional cask preferences from $OPTIONAL_CASK_ENV_FILE"
  fi
}

write_optional_cask_env() {
  mkdir -p "$(dirname "$OPTIONAL_CASK_ENV_FILE")"
  cat > "$OPTIONAL_CASK_ENV_FILE" <<EOF
# Auto-generated by setup.sh - optional cask preferences
export BREW_INSTALL_VIRTUALBOX=${BREW_INSTALL_VIRTUALBOX:-0}
export BREW_INSTALL_BRAVE_BROWSER=${BREW_INSTALL_BRAVE_BROWSER:-0}
export BREW_INSTALL_VLC=${BREW_INSTALL_VLC:-0}
export BREW_INSTALL_SPOTIFY=${BREW_INSTALL_SPOTIFY:-0}
EOF
  print_success "Saved optional cask preferences to $OPTIONAL_CASK_ENV_FILE"
}

# ============================================
# Pre-flight checks
# ============================================

print_header "Pre-flight Checks"

# Check if running on macOS
if [[ "$OSTYPE" != "darwin"* ]]; then
  print_error "This script is designed for macOS only."
  exit 1
fi

print_success "Running on macOS"

# Ensure Xcode Command Line Tools are available for git/Homebrew
if ! xcode-select -p >/dev/null 2>&1; then
  print_info "Installing Xcode Command Line Tools..."
  xcode-select --install || true
  print_warning "Command Line Tools install has been initiated. Re-run setup after it completes."
  exit 1
fi

print_success "Xcode Command Line Tools detected"

load_optional_cask_env

# ============================================
# Optional cask selection (VirtualBox, Brave, VLC, Spotify)
# ============================================

print_header "Optional Casks"

configure_optional_cask() {
  local var_name="$1"
  local label="$2"
  local description="$3"
  local current="${!var_name:-}"
  local normalized_current
  normalized_current="$(normalize_bool "$current")"
  local default_label=$([[ "$normalized_current" == "1" ]] && echo "enabled" || echo "disabled")

  if [[ -n "$current" ]]; then
    print_info "$label default: $default_label (current setting)"
  else
    print_info "$label default: $default_label"
  fi

  # Skip prompting when explicitly requested or when no TTY is available
  if [[ "${DOTFILES_SKIP_OPTIONAL_PROMPTS:-0}" == "1" || ! has_tty ]]; then
    export "$var_name"="$normalized_current"
    print_info "Skipping prompt for $label; using $var_name=${!var_name} (set $var_name=1 to enable)."
    return
  fi

  local prompt_default="n"
  if [[ -n "$current" ]]; then
    prompt_default=$([[ "$normalized_current" == "1" ]] && echo "y" || echo "n")
  fi

  local prompt="Install ${label}? (${description})"
  if prompt_yes_no "$prompt" "$prompt_default"; then
    export "$var_name"=1
    print_success "$label enabled ($var_name=1)"
  else
    export "$var_name"=0
    print_info "$label skipped ($var_name=0)"
  fi
}

configure_optional_cask "BREW_INSTALL_VIRTUALBOX" "VirtualBox" "Full VM hypervisor"
configure_optional_cask "BREW_INSTALL_BRAVE_BROWSER" "Brave Browser" "Privacy-focused browser"
configure_optional_cask "BREW_INSTALL_VLC" "VLC" "Versatile media player"
configure_optional_cask "BREW_INSTALL_SPOTIFY" "Spotify" "Music streaming client"

write_optional_cask_env

# Keep sudo alive so Homebrew/cask installs only prompt once
if command -v sudo >/dev/null 2>&1; then
  print_info "Refreshing sudo credentials to avoid repeated prompts..."
  if sudo -v; then
    # Background keepalive until this script exits
    while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &
    SUDO_KEEPALIVE_PID=$!
    trap '[[ -n "$SUDO_KEEPALIVE_PID" ]] && kill "$SUDO_KEEPALIVE_PID" 2>/dev/null || true' EXIT
    print_success "Sudo session refreshed"
  else
    print_warning "Could not refresh sudo credentials. You may be prompted during installs."
  fi
else
  print_warning "sudo not available. Continuing without elevated privileges."
fi

# Get the directory where this script is located
DOTFILES_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
print_info "Dotfiles directory: $DOTFILES_DIR"

cd "$DOTFILES_DIR"

# ============================================
# Step 1: Install Homebrew
# ============================================

print_header "Step 1: Homebrew Installation"

if command -v brew &> /dev/null; then
  print_success "Homebrew is already installed ($(brew --version | head -n 1))"
else
  print_info "Installing Homebrew..."
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

  # Add Homebrew to PATH for Apple Silicon Macs
  if [[ -f "/opt/homebrew/bin/brew" ]]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
  fi

  print_success "Homebrew installed successfully"
fi

# ============================================
# Step 2: Install packages from Brewfile
# ============================================

print_header "Step 2: Installing Packages from Brewfile"

if [[ -f "$DOTFILES_DIR/Brewfile" ]]; then
  print_info "Running brew bundle install..."
  brew bundle install --file="$DOTFILES_DIR/Brewfile" --verbose
  print_success "All packages installed from Brewfile"
else
  print_error "Brewfile not found at $DOTFILES_DIR/Brewfile"
  exit 1
fi

# ============================================
# Step 3: Setup mise (version manager)
# ============================================

print_header "Step 3: Setting up mise"

if [[ -x "$DOTFILES_DIR/install_mise.sh" ]]; then
  "$DOTFILES_DIR/install_mise.sh"
else
  print_warning "install_mise.sh not found or not executable, skipping..."
fi

# ============================================
# Step 4: Setup dotfiles with GNU Stow
# ============================================

print_header "Step 4: Setting up Dotfiles with GNU Stow"

if [[ -x "$DOTFILES_DIR/stow_setup.sh" ]]; then
  "$DOTFILES_DIR/stow_setup.sh"
else
  print_warning "stow_setup.sh not found or not executable, skipping..."
fi

# ============================================
# Step 5: Configure Git identity
# ============================================

print_header "Step 5: Configuring Git Identity"

configure_git_identity() {
  local existing_name existing_email existing_signing
  existing_name="$(git config --global --get user.name 2>/dev/null || true)"
  existing_email="$(git config --global --get user.email 2>/dev/null || true)"
  existing_signing="$(git config --global --get user.signingkey 2>/dev/null || true)"

  local default_name="${GIT_USER_NAME:-${existing_name:-$DEFAULT_GIT_NAME}}"
  local default_email="${GIT_USER_EMAIL:-${existing_email:-$DEFAULT_GIT_EMAIL}}"
  local default_signing="${GIT_USER_SIGNINGKEY:-${existing_signing:-$DEFAULT_GIT_SIGNINGKEY}}"

  if [[ -n "$default_name" || -n "$default_email" || -n "$default_signing" ]]; then
    print_info "Git identity defaults:"
    [[ -n "$default_name" ]] && print_info "  user.name:  $default_name"
    [[ -n "$default_email" ]] && print_info "  user.email: $default_email"
    [[ -n "$default_signing" ]] && print_info "  signingkey: $default_signing"
  fi

  local final_name="$default_name"
  local final_email="$default_email"
  local final_signing="$default_signing"

  if [[ "${DOTFILES_SKIP_GIT_PROMPTS:-0}" == "1" ]]; then
    if [[ -z "$default_name" && -z "$default_email" ]]; then
      print_info "Skipping Git identity prompts (DOTFILES_SKIP_GIT_PROMPTS=1) with no defaults; leaving existing config untouched."
      return
    fi
    print_info "Skipping Git identity prompts (DOTFILES_SKIP_GIT_PROMPTS=1); using provided defaults."
  elif ! has_tty; then
    if [[ -z "$default_name" && -z "$default_email" ]]; then
      print_info "No TTY and no defaults available; skipping Git identity configuration."
      return
    fi
  else
    local use_defaults="y"
    if [[ -n "$default_name" || -n "$default_email" || -n "$default_signing" ]]; then
      if prompt_yes_no "Use the default Git identity above?" "y"; then
        use_defaults="y"
      else
        use_defaults="n"
      fi
    fi

    if [[ "$use_defaults" != "y" ]]; then
      final_name="$(prompt_with_default "Git user.name" "$default_name")"
      while has_tty && [[ -z "$final_name" ]]; do
        print_warning "Git user.name is required."
        final_name="$(prompt_with_default "Git user.name" "$final_name")"
      done

      final_email="$(prompt_with_default "Git user.email" "$default_email")"
      while has_tty && [[ -z "$final_email" ]]; do
        print_warning "Git user.email is required."
        final_email="$(prompt_with_default "Git user.email" "$final_email")"
      done

      final_signing="$(prompt_with_default "Git signingkey (optional)" "$default_signing")"
    fi
  fi

  if [[ -z "$final_name" || -z "$final_email" ]]; then
    print_warning "Git identity not updated (missing name/email)."
    return
  fi

  mkdir -p "$(dirname "$GIT_LOCAL_CONFIG_FILE")"
  {
    echo "[user]"
    echo "    name = $final_name"
    echo "    email = $final_email"
    if [[ -n "$final_signing" ]]; then
      echo "    signingkey = $final_signing"
    fi
  } > "$GIT_LOCAL_CONFIG_FILE"

  print_success "Git identity configured in $GIT_LOCAL_CONFIG_FILE"
  print_info "Git user.name: $final_name"
  print_info "Git user.email: $final_email"
  if [[ -n "$final_signing" ]]; then
    print_info "Git signingkey: $final_signing"
  fi
}

configure_git_identity

# ============================================
# Step 6: Setup GnuPG (GPG)
# ============================================

print_header "Step 6: Setting up GnuPG"

if [[ -x "$DOTFILES_DIR/setup_gnupg.sh" ]]; then
  "$DOTFILES_DIR/setup_gnupg.sh"
else
  print_warning "setup_gnupg.sh not found or not executable, skipping..."
fi

# ============================================
# Step 7: Setup VSCode extensions
# ============================================

print_header "Step 7: Setting up VSCode Extensions"

# Allow skipping via env; otherwise auto-run if VSCode CLI is available
if [[ "${SKIP_VSCODE_EXTENSIONS:-0}" == "1" ]]; then
  print_info "Skipping VSCode extensions setup (SKIP_VSCODE_EXTENSIONS=1)"
elif ! command -v code >/dev/null 2>&1; then
  print_warning "VSCode CLI 'code' not found. Install VSCode and run: make vscode"
elif [[ -x "$DOTFILES_DIR/vscode_setup.sh" ]]; then
  "$DOTFILES_DIR/vscode_setup.sh"
else
  print_warning "vscode_setup.sh not found or not executable, skipping..."
fi

# ============================================
# Final Steps
# ============================================

print_header "Setup Complete!"

echo "Your development environment has been set up successfully!"
echo ""
echo "📋 Next Steps:"
echo ""
echo "1. Restart your terminal or run:"
echo "   ${GREEN}source ~/.zshrc${NC}"
echo ""
echo "2. Verify installations:"
echo "   ${GREEN}brew doctor${NC}        # Check Homebrew health"
echo "   ${GREEN}mise doctor${NC}        # Check mise health"
echo "   ${GREEN}mise list${NC}          # Show installed versions"
echo ""
echo "3. Install additional language versions with mise:"
echo "   ${GREEN}mise use node@20${NC}   # Install Node.js 20"
echo "   ${GREEN}mise use python@3.12${NC} # Install Python 3.12"
echo ""
echo "4. Explore modern CLI tools:"
echo "   ${GREEN}ls${NC}                 # Now uses 'eza' with icons"
echo "   ${GREEN}cat file.txt${NC}       # Now uses 'bat' with syntax highlighting"
echo "   ${GREEN}cd${NC}                 # Now uses 'zoxide' for smart navigation"
echo ""
echo "💡 Tips:"
echo "   - Use 'z <dir>' for smart directory jumping"
echo "   - Use 'fzf' with Ctrl+R for command history search"
echo "   - Use 'brewup' alias to update all Homebrew packages"
echo ""
echo "📖 For more information, check the README.md"
echo ""
